/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.gui;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projeto.erro.ConexaoException;
import projeto.erro.GeralException;
import projeto.modelo.fachada.Fachada;
import projeto.modelo.to.*;

/**
 *
 * @author Sandro
 */
public class GuiClienteM extends javax.swing.JDialog {

    ArrayList<PessoaJuridica> listaPJ = null;
    ArrayList<PessoaFisica> listaPF = null;
    ArrayList<Cliente> listaCli = null;
    public static Fachada fachada = new Fachada();
    /**
     * Creates new form GuiClienteM
     */
    public GuiClienteM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    GuiClienteM() {
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jbSair = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioBPF = new javax.swing.JRadioButton();
        jRadioBPJ = new javax.swing.JRadioButton();
        jFormatTextCPF = new javax.swing.JFormattedTextField();
        jFormatTextCNPJ = new javax.swing.JFormattedTextField();
        jTextNomeRazao = new javax.swing.JTextField();
        jbPesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Listagem");

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Cliente", "Título 2", "Título 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtro de Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setText("CPF.:");

        jLabel2.setText("CNPJ.:");

        jLabel3.setText("Nome / Razão Social.:");

        buttonGroup1.add(jRadioBPF);
        jRadioBPF.setText("PessoaFísica");
        jRadioBPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBPFActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioBPJ);
        jRadioBPJ.setText("PessoaJurídica");
        jRadioBPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBPJActionPerformed(evt);
            }
        });

        try {
            jFormatTextCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormatTextCPF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormatTextCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormatTextCPFActionPerformed(evt);
            }
        });

        try {
            jFormatTextCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormatTextCNPJ.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormatTextCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormatTextCNPJActionPerformed(evt);
            }
        });

        jTextNomeRazao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeRazaoActionPerformed(evt);
            }
        });

        jbPesquisa.setText("Pesquisa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNomeRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioBPF)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioBPJ))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormatTextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(jbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormatTextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jFormatTextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormatTextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNomeRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioBPF)
                            .addComponent(jRadioBPJ))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jbPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        // TODO add your handling code here:
        GuiPessoaFisicaNovoM pf = new GuiPessoaFisicaNovoM();
        pf.setVisible(true);
        //atualizarTabela();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        // TODO add your handling code here:
        limparCampos();
       // atualizarTabela();

    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
       // alterarFornecedor();
        //atualizarTabela();

    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        //excluirFornecedor();
        //atualizarTabela();

    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jFormatTextCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormatTextCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormatTextCPFActionPerformed

    private void jFormatTextCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormatTextCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormatTextCNPJActionPerformed

    private void jTextNomeRazaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeRazaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeRazaoActionPerformed

    private void jRadioBPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBPFActionPerformed

    private void jRadioBPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBPJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiClienteM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiClienteM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiClienteM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiClienteM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                GuiClienteM dialog = new GuiClienteM(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
      /*  private void alterarFornecedor() {
        int resposta;
        try {
            Fornecedor fOld = listaFornecedor.get(jTableListaFornecedor.getSelectedRow());

            resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente Alterar?", "", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                GuiFornecedorAlterar guiFornecedorAlterar = new GuiFornecedorAlterar();
                guiFornecedorAlterar.jFormattedTextFieldSaidaCNPJ.setText(fOld.getFornecedores_CNPJ());
                guiFornecedorAlterar.jTextFieldSaidaRS.setText(fOld.getFornecedores_RazaoSocial());
                guiFornecedorAlterar.jFormattedTextFieldSaidaCEP.setText(fOld.getEnderecos_CEP());
                guiFornecedorAlterar.jTextFieldSaidaLog.setText(fOld.getEnderecos_Logradouro());
                guiFornecedorAlterar.jFormattedTextFieldSaidaNumero.setText(String.valueOf(fOld.getFornecedores_NumeroResidencia()));
                guiFornecedorAlterar.jTextFieldSaidaCidade.setText(fOld.getCidades_Nome());
                guiFornecedorAlterar.setVisible(true);
            }
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "Selecione um Registro!");
        }
    }*/
    
  /*  private void excluirFornecedor() {
       int resposta;

        try {
            Fornecedor f = listaFornecedor.get(jTableListaFornecedor.getSelectedRow());

            resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente Apagar ?", "", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                Fornecedor fConsult = fachada.consultarForCNPJ(f.getFornecedores_CNPJ());
                if (fConsult != null) {
                    fachada.excluirFornecedor(fConsult.getFornecedores_CNPJ());
                }
            }
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "Selecione um Registro!");
        } catch (GeralException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }*/
    
    private void pesquisarCNPJ() throws ConexaoException {
        String str_cnpj;
        String PessoaJuridica_CNPJ;
        try {
            str_cnpj = jFormatTextCNPJ.getText();
            str_cnpj = str_cnpj.replace('.', ' ');
            str_cnpj = str_cnpj.replace('/', ' ');
            str_cnpj = str_cnpj.replace('-', ' ');
            str_cnpj = str_cnpj.replaceAll(" ", "");
            PessoaJuridica_CNPJ = str_cnpj;
            //if ((PessoaJuridica_CNPJ == null) || (PessoaJuridica_CNPJ.equals(""))) {
                listaPJ = (ArrayList<PessoaJuridica>) fachada.listarPessoaJuridica();
            //} else {
                
            //}
        } catch (GeralException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        DefaultTableModel modelo = geramodeloPJ(listaPJ);
        jTableCliente.setModel(modelo);
    }
    
    private void pesquisarNome() throws ConexaoException {
        try {
            //if ((jTextNomeRazao.getText() == null) || (jTextNomeRazao.getText().equals(""))) {
                listaCli = (ArrayList<Cliente>) fachada.listarTodosCliente();
            //} else {
               // listaFornecedor = (ArrayList<Fornecedor>) fachada.listarFornecedorRazaoSocial(jTextFieldEntradaRS.getText());
            //}
        } catch (GeralException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        DefaultTableModel modelo = geramodelo(listaCli);
        jTableCliente.setModel(modelo);
    }
    
    private void pesquisarCPF() throws ConexaoException {
        String str_cpf;
        String pF_CPF;
        try {
            str_cpf = jFormatTextCPF.getText();
            str_cpf = str_cpf.replace('-', ' ');
            str_cpf = str_cpf.replaceAll(" ", "");
            pF_CPF = str_cpf;
            //if ((fornecedores_CEP == null) || (fornecedores_CEP.equals(""))) {
                listaPF = (ArrayList<PessoaFisica>) fachada.listarPessoaFisica();
            //} else {
                //listaFornecedor = (ArrayList<Fornecedor>) fachada.listarFornecedorCEP(fornecedores_CEP);
            //}
        } catch (GeralException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        DefaultTableModel modeloPF = geramodeloPF(listaPF);
        jTableCliente.setModel(modeloPF);
    }
    
    
  /*  public void atualizarTabela() {
        try {
            listaFornecedor = (ArrayList<Fornecedor>) fachada.listarFornecedor();
        } catch (GeralException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        DefaultTableModel modelo = geramodelo(listaFornecedor);
        jTableListaFornecedor.setModel(modelo);
    }*/
    
    
    private void limparCampos() {
        jFormatTextCPF.setValue(null);
        jFormatTextCNPJ.setValue(null);
        jTextNomeRazao.setText("");
    }
    
    private DefaultTableModel geramodelo(ArrayList<Cliente> listaCliente) {
        DefaultTableModel modeloCli = new DefaultTableModel();
        modeloCli.addColumn("Nome/Razao Social");
        modeloCli.addColumn("Tipo");

        ArrayList<String> valores;
        int i = 0;
        for (Cliente cli : listaCliente) {
            valores = new ArrayList<String>();
            //valores.add(cli.getNome());
            valores.add(cli.getClientes_Tipo());
            /*valores.add(f.getEnderecos_Logradouro());
            valores.add(String.valueOf(f.getFornecedores_NumeroResidencia()));
            valores.add(f.getCidades_Nome());
            valores.add(f.getEnderecos_CEP());*/
            modeloCli.insertRow(i, valores.toArray());
            i++;
        }
        return modeloCli;
    }

        private DefaultTableModel geramodeloPF(ArrayList<PessoaFisica> listaPF) {
        DefaultTableModel modeloPF = new DefaultTableModel();
        modeloPF.addColumn("Nome");
        modeloPF.addColumn("CPF");

        ArrayList<String> valores;
        int i = 0;
        for (PessoaFisica pf : listaPF) {
            valores = new ArrayList<String>();
           // valores.add(pf.getNome());
            valores.add(pf.getPessoasFisica_CPF());
            /*valores.add(f.getEnderecos_Logradouro());
            valores.add(String.valueOf(f.getFornecedores_NumeroResidencia()));
            valores.add(f.getCidades_Nome());
            valores.add(f.getEnderecos_CEP());*/
            modeloPF.insertRow(i, valores.toArray());
            i++;
        }
        return modeloPF;
    }

        private DefaultTableModel geramodeloPJ(ArrayList<PessoaJuridica> listaPJ) {
        DefaultTableModel modeloPJ = new DefaultTableModel();
        modeloPJ.addColumn("Razao Social");
        modeloPJ.addColumn("CNPJ");

        ArrayList<String> valores;
        int i = 0;
        for (PessoaJuridica PJ : listaPJ) {
            valores = new ArrayList<String>();
            valores.add(PJ.getPessoasJuridica_RazaoSocial());
            valores.add(PJ.getPessoasJuridica_CNPJ());
            /*valores.add(f.getEnderecos_Logradouro());
            valores.add(String.valueOf(f.getFornecedores_NumeroResidencia()));
            valores.add(f.getCidades_Nome());
            valores.add(f.getEnderecos_CEP());*/
            modeloPJ.insertRow(i, valores.toArray());
            i++;
        }
        return modeloPJ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jFormatTextCNPJ;
    private javax.swing.JFormattedTextField jFormatTextCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioBPF;
    private javax.swing.JRadioButton jRadioBPJ;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextNomeRazao;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisa;
    private javax.swing.JButton jbSair;
    // End of variables declaration//GEN-END:variables
}
